# Site settings
title: Coaltrains Coffee Shop and Gallery
email: coaltrainscoffeeshopgallery@gmail.com
url: https://coaltrainscoffeeshopgallery.co.uk/
description: "Coaltrains Coffee Shop and Gallery, located on Barry Train Station, CF62 7AE"
keywords: "Coaltrains, Coffee, Shop, Gallery, Barry, Train, Station, Trainstation, CF62 7AE, CF627AE, Jazz, Music"
skills: "We're all on a journey"
meta_author: Underdown Ieuan



# Google webmaster tools
google_verify:

# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Contact form:
# - static : pass through formspree.io to validate email sending
# - disqus : replace contact form by disqus thread
# - comment the line below if you want to stick with the default PHP contact form
contact: static

# If you use disqus you need disqus shortname
# https://help.disqus.com/customer/portal/articles/466208
disqus_shortname: myshortname

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: EB8AFF #80B3FF
  primary-rgb: "235,138,255" #"128,179,255"
  secondary: FCCF3F #FD6E8A
  secondary-dark: FCBA3F #A2122F

# Footer settings
footer:
  copyright: Coaltrains Coffee Shop and Gallery
  location: Barry Train Station

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: facebook
    url: https://www.facebook.com/coaltrainscoffeeshop/?locale=en_GB
  - title: instagram
    url: https://www.instagram.com/coaltrains_coffee_shop_gallery/

# Postal address (add as many lines as necessary)
address:
  - line: Barry Train Station
  - line: Broad St, Barry, CF62 7AE

# Credits content
credits: 'All rights belong to Coaltrains Coffee Shop and Gallery.'

# Build settings
markdown: kramdown
permalink: pretty

include:
  - _pages

#for posts
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      permalink: ""

baseurl: ""

future: true